#!/bin/bash
# 242Go — Church Onboarding Setup Wizard
# Run this script on a new church's Mac Mini or mini PC
# Usage: bash setup-church.sh

set -e

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "   242Go Leadership Pipeline"
echo "   Church Onboarding Setup Wizard"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "This wizard will configure your 242Go system."
echo "Have these ready before continuing:"
echo "  • Your church's Telegram bot token (from @BotFather)"
echo "  • Your Telegram user ID (from @userinfobot)"
echo "  • Your Supabase project URL and service role key"
echo "  • Your Anthropic API key"
echo "  • Your Cloudflare tunnel token (free at cloudflare.com)"
echo ""
read -p "Press ENTER to begin..."

# ── Collect church info ──────────────────────
echo ""
echo "── Step 1: Church Information ──"
read -p "Church ID (slug, no spaces — e.g. hope-church-atl): " CHURCH_ID
read -p "Church name (e.g. Hope Church Atlanta): " CHURCH_NAME
read -p "Pastor's full name: " PASTOR_NAME
read -p "City: " CITY
read -p "State (2 letters): " STATE

echo ""
echo "── Step 2: Telegram ──"
read -p "Bot token (from @BotFather): " BOT_TOKEN
read -p "Your Telegram user ID (admin): " ADMIN_ID
read -p "App URL (your Cloudflare tunnel URL, e.g. https://your-church.242go.app): " APP_URL

echo ""
echo "── Step 3: Supabase ──"
read -p "Supabase URL (https://xxx.supabase.co): " SUPABASE_URL
read -p "Supabase service role key: " SUPABASE_KEY

echo ""
echo "── Step 4: Anthropic ──"
read -p "Anthropic API key (sk-ant-...): " ANTHROPIC_KEY

echo ""
echo "── Step 5: Cloudflare Tunnel ──"
read -p "Cloudflare tunnel token: " CF_TOKEN

echo ""
echo "── Step 6: Notion CRM (optional — press ENTER to skip) ──"
read -p "Notion API key (or ENTER to skip): " NOTION_KEY
read -p "Notion database ID (or ENTER to skip): " NOTION_DB

# ── Write .env.local ─────────────────────────
echo ""
echo "Writing configuration..."

cat > .env.local <<EOF
# 242Go — ${CHURCH_NAME}
# Generated by setup-church.sh

CHURCH_ID=${CHURCH_ID}
CHURCH_NAME=${CHURCH_NAME}
PASTOR_NAME=${PASTOR_NAME}

TELEGRAM_BOT_TOKEN=${BOT_TOKEN}
NEXT_PUBLIC_APP_URL=${APP_URL}
ADMIN_TELEGRAM_IDS=${ADMIN_ID}

ANTHROPIC_API_KEY=${ANTHROPIC_KEY}

NEXT_PUBLIC_SUPABASE_URL=${SUPABASE_URL}
SUPABASE_SERVICE_ROLE_KEY=${SUPABASE_KEY}

NOTION_API_KEY=${NOTION_KEY}
NOTION_DATABASE_ID=${NOTION_DB}

CLOUDFLARE_TUNNEL_TOKEN=${CF_TOKEN}

CRON_SECRET=$(openssl rand -hex 32)
EOF

echo "✅ .env.local written"

# ── Start Docker stack ───────────────────────
echo ""
echo "── Starting 242Go Docker stack ──"
docker compose up -d --build
echo "✅ Docker stack started"

# ── Register webhook with Telegram ──────────
echo ""
echo "── Registering Telegram webhook ──"
sleep 5  # Wait for app to be ready

WEBHOOK_URL="${APP_URL}/api/webhook"
RESPONSE=$(curl -s "https://api.telegram.org/bot${BOT_TOKEN}/setWebhook" \
  -d "url=${WEBHOOK_URL}" \
  -d "allowed_updates=[\"message\"]")

if echo "$RESPONSE" | grep -q '"ok":true'; then
  echo "✅ Webhook registered: ${WEBHOOK_URL}"
else
  echo "⚠️  Webhook registration failed. Run manually:"
  echo "   curl https://api.telegram.org/bot${BOT_TOKEN}/setWebhook?url=${WEBHOOK_URL}"
fi

# ── Done ─────────────────────────────────────
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "   ✅ ${CHURCH_NAME} is live on 242Go!"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Next steps:"
echo "  1. Open Telegram and send /start to your bot"
echo "  2. Add your Supabase schema (supabase_schema.sql + supabase_schema_multichurch.sql)"
echo "  3. Send the April 1 announcement when ready"
echo ""
echo "Dashboard: ${APP_URL}"
echo "Bot:       @$(curl -s "https://api.telegram.org/bot${BOT_TOKEN}/getMe" | python3 -c 'import sys,json; print(json.load(sys.stdin)["result"]["username"])' 2>/dev/null || echo 'your_bot')"
echo ""
